### ISSUE TITLE
H1_ 호가 잔량 필드에서 일정 필드 데이타 누락 현상

### ISSUE THREAD

**Issue by blueysnow2** [ScriptonBasestar-Grabber/grabber-stock-api-cs#1]
지금도 프로그램 유지 보수 하시는지 모르겠습니다.
코드를 살펴보다가 보니, 코스피 호가 잔량 필드 중에서 일부가 누락이 되는 것을 발견했습니다.

hotime | offerho1 | bidho1 | offerrem1 | bidrem1 | offerho2 | bidho2 | offerrem2 | bidrem2 | offerho3 | bidho3 | offerrem3 | bidrem3 | offerho4 | bidho4 | offerrem4 | bidrem4 | offerho5 | bidho5 | offerrem5 | bidrem5 | offerho6 | bidho6 | offerrem6 | bidrem6 | offerho7 | bidho7 | offerrem7 | bidrem7

위에 보이는 부분이 .csv 파일에서 찍히는 데이타 필드입니다.
나머지, 8,9,10 호가 부분은 누락이 되어서 찍히지 않네요.

**Comment by blueysnow2** [comment]
ReadResFile.cs

if (lines[idxLine].TrimStart().StartsWith("begin"))
                    {
                        idxLine++;
                        LOG.Info("1.idxLine: " + idxLine);
                        **for (int idxInner = idxLine; idxInner < lines[idxLine].Length; idxInner++)**                        
                        {

==>

if (lines[idxLine].TrimStart().StartsWith("begin"))
                    {
                        idxLine++;
                        LOG.Info("1.idxLine: " + idxLine);
                        //for (int idxInner = idxLine; idxInner < lines[idxLine].Length; idxInner++)
                        **for (int idxInner = idxLine; idxInner < lines.Length; idxInner++)**
                        {

위와 같이 볼드 처리한 부분을 변경했습니다.
OutBlock 읽어 들이는 부분에서 끝까지 읽지 못하고, lines[idxLine].Length 만큼만 읽게 되어서, 중간에 뜅김 현상이 있었네요.

**Comment by archmagece** [comment]
감사합니다. 수정해서 올렸습니다.
